import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";
import { FooterNav } from "./components/footer-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SHPE at Cornell",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // Path to your favicon
    shortcut: "/favicon.png",
    apple: "/apple-touch-icon.png", // Optional: For Apple devices
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#001F5B" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="text-white text-center">
          <Navigation />
          <hr />
        </header>
        {children}
        <footer className="bg-[#001F5B] text-white">
          <FooterNav />
          <hr />
        </footer>
      </body>
    </html>
  );
}
